### ISSUE TITLE
Style site TOC (on the left) according to design

### ISSUE THREAD

**Issue by tbrlpld** [wagtail/sphinx_wagtail_theme#85] opened 2021-04-09 06:40 UTC
https://www.figma.com/file/hFjWqQeEjGd8NtTsEHcc4i/Wagtail-Documentation-wagtail.io?node-id=0%3A1

<img width="234" alt="Screen Shot 2021-04-08 at 20 41 26" src="https://user-images.githubusercontent.com/24797493/114139476-d0cead00-98aa-11eb-8adc-0519ba5890e0.png">

**Comment by lb-** [comment] 2022-08-18 23:37
This is a duplicate of #59 and has been resolved via https://github.com/wagtail/sphinx_wagtail_theme/pull/191

If there are further refinements needed we can raise a new issue with specific feedback.

**Closed by lb-** 2022-08-18 23:37 UTC
