### ISSUE TITLE
Hyperlink in docs invisible on Safari

### ISSUE THREAD

**Issue by nutjob4life** [wagtail/sphinx_wagtail_theme#181] opened 2022-06-24 16:58 UTC
### Pertinent section of the Wagtail docs

In the [Wagtail 3.0 release notes](https://docs.wagtail.org/en/stable/releases/3.0.html), the word "MyST" is hyperlinked. On Chrome and Firefox, it appears with a cyan-colored underline.

However, under desktop Safari 15.5 (on macOS 12.4) and mobile Safari 15.5 (on iOS 15.5), the underline is not visible. It's random chance that I happened to mouse over it and gasped audibly (okay, not really) when my cursor changed.

(And yes, I use Safari since most of my users do too and it's easier to catch problems early that way.)

### Details

Here's a screenshot:

![Screen Shot 2022-06-24 at 11 57 37 AM](https://user-images.githubusercontent.com/814813/175607745-7af37f38-87aa-4ced-89b9-5a40474cb4b0.png)

**Comment by zerolab** [comment] 2022-06-24 21:26
Hey @nutjob4life,

Thank you for reporting this. I moved the issue to https://github.com/wagtail/sphinx_wagtail_theme as we use it for the docs theme and I can confirm the issue is present for https://sphinx-wagtail-theme.readthedocs.io/en/latest/ too

**Comment by PaarthAgarwal** [comment] 2022-06-25 05:33
We fixed this issue over there. Is wagtail using the latest version of sphynx_wagtail_theme?

**Comment by lb-** [comment] 2022-06-25 09:02
Yeah. This does look like a duplicate of https://github.com/wagtail/sphinx_wagtail_theme/issues/155

@nutjob4life can you please check the latest docs on safari to confirm. 

https://docs.wagtail.org/en/latest/releases/3.0.html

**Comment by PaarthAgarwal** [comment] 2022-06-25 09:36
> Yeah. This does look like a duplicate of #155
> 
> @nutjob4life can you please check the latest docs on safari to confirm.
> 
> https://docs.wagtail.org/en/latest/releases/3.0.html

I can't test the safari issue but the Wagtail docs aren't using sticky and scrollable tocs which I've added. So I think the safari issue should be existing as well.

**Comment by lb-** [comment] 2022-06-25 10:19
Ahh yeah I see - that change has not been released yet. 
Not sure on the process for a release but I'll mention in the core team chat. 

I'll close this issue though as a duplicate - once the Sphinx theme update is released and adopted by Wagtail the issue will be resolved.

**Closed by lb-** 2022-06-25 10:19 UTC
Labels: bug

**Comment by zerolab** [comment] 2022-06-25 11:25
Thank you @PaarthAgarwal and @lb- for being on top of this

**Comment by nutjob4life** [comment] 2022-06-26 19:29
> Yeah. This does look like a duplicate of #155
> 
> @nutjob4life can you please check the latest docs on safari to confirm.
> 
> https://docs.wagtail.org/en/latest/releases/3.0.html

Still not seeing underlines on desktop Safari even after a force reload and cache-busting—except on hover, @lb- 

![Screen Shot 2022-06-26 at 2 28 02 PM](https://user-images.githubusercontent.com/814813/175830723-9329c827-8464-45ba-a063-840412ce0f59.png)

But, taking the conversation over to the [duplicate issue now](https://github.com/wagtail/sphinx_wagtail_theme/issues/155)!

**Comment by lb-** [comment] 2022-06-27 05:22
@nutjob4life sorry for the confusion - this fix has not been released yet  (only on the main branch) so we will need to wait until the team do a new release of this package to see the fix go live.

I have asked the core team what is the process for doing a release (as in deciding the timing) and hopefully will get an answer soon.
